### ISSUE TITLE
Date defendant's address last known - provide date or write in

### ISSUE THREAD

**Issue by aubsticle** [SuffolkLITLab/docassemble-ServiceByAltMeansAndDiligentSearch#14]
give them option to provide a written guess or date selector 
good example of this on the 209A

**Comment by zaranlilia** [comment]
Added this to the question, not sure if it was the correct code, so I have not closed this issue. 

  - 'Date of last contact': last_contact_date
    datatype: date
  - 'Written Guess': written_guess 

@stevejaubz

**Comment by stevejaubz** [comment]
`id: When did the defendant last live at this address?
question: |
  When did  ${ other_parties[1-1].name } last live at ${ other_parties[1-1].address } ?
subquestion: |
  This can be a guess or the exact date 
fields:
  - 'Do not know': do_not_know
    datatype: yesno
  - 'Date': date_last_known
    datatype: date
    show if: 
      variable: do_not_know
      is: False
  - 'Guess': date_last_known
    show if:
      variable: do_not_know
      is: True`

**Comment by aubsticle** [comment]
adding block into slack for basic show/hide

**Comment by zaranlilia** [comment]
Aubrie's fix of the code was a success, there was just a problem with the variables used that was breaking the court. Variables have been updated and written guess is included but if the use clicks "I don't know" and write in their guess the interview won't go to the next question.

**Comment by zaranlilia** [comment]
Fixed the conditional if statement that was breaking the code
