### ISSUE TITLE
Types of contact - split by phone and text into two options

### ISSUE THREAD

**Issue by aubsticle** [SuffolkLITLab/docassemble-ServiceByAltMeansAndDiligentSearch#19]
move phone and text to AFTER selector and make those conditional

**Comment by zaranlilia** [comment]
I split phone and text into two options in the search_question.yml and created a new question for text option; have not made them conditional

**Comment by aubsticle** [comment]
variable names were changed `check_phone_text `is now two fields (`check_phone` and `check_text`) but order block still container old variable so the code is throwing an error. 

`check_phone` and `check_text` should still check the same box on the PDF which is currently titled `check_phone_text `  - need to ensure that selction of either of the two fields will cause the field on the PDF to fill out.

**Comment by zaranlilia** [comment]
order block was updated and now includes new variables (to split up text and call)

ran the interview and it was successful; pushed new code to GitHub

**Comment by aubsticle** [comment]
in attachment block make sure that either variable checks off  variable `check_phone_text `in PDF

**Comment by zaranlilia** [comment]
specified in attachment block that both check_phone or check_text fills in the field where "check_phone_text" used to be
order block was updated to make all responses conditional on the check box selected

**Comment by aubsticle** [comment]
issue - if you select phone and text right now nothing fills in the box because it is OR. Need to switch to either or both

**Comment by zaranlilia** [comment]
Added line "phone_response": ${ text_response }" and that fixes the issue with the response box. Added line “"check_phone_text": ${ check_text }” and that fixes the issue with the check box.
