### ISSUE TITLE
correct question - Who are you? - currently a place holder 

### ISSUE THREAD

**Issue by aubsticle** [SuffolkLITLab/docassemble-ServiceByAltMeansAndDiligentSearch#22]
User choice 
209A probably has a good example that allows the user to select advocate or plaintiff and changes role

**Comment by aubsticle** [comment]
starting to resolve in branch user_role_attorney_plaintiff

**Comment by aubsticle** [comment]
user role can now pick attorney plaintiff - need to update conditional language in questions

**Comment by aubsticle** [comment]
user role will only add in attorney information for now at the end - will not change anything about the interview

**Comment by zaranlilia** [comment]
for MVP user is only a pro se user; however, in class Quinten mentioned making an additional question regarding whether or not the user is an attorney and having a kick out screen if the user is an attorney
