### ISSUE TITLE
military check 

### ISSUE THREAD

**Issue by aubsticle** [SuffolkLITLab/docassemble-ServiceByAltMeansAndDiligentSearch#43]
make the check more clear - if they check that box add instructions to attach or is that post MVP 

Military. I went to the Defense of Manpower Data Center (DMDC) website, https://scra.dmdc.osd.mil , and submitted
a "Single Record Request" to obtain a report certifying the active duty status of the person, a copy of which is
attached.

**Comment by aubsticle** [comment]
added help buttons

**Comment by zaranlilia** [comment]
Created question that asks for user to attach a copy of the Single Record Request they filled out. Still need to make the attachment a part of the PDF packet that is downloadable for user.

**Comment by zaranlilia** [comment]
Made the attachment a part of the PDF packet; changing the style of question 

- going to ask if the defendant is in the military; if yes then
- asking whether or not they used the Single Request Record; if yes then
- go into question about uploading a copy of the request
